#!/bin/bash
# Health check script for PostgreSQL HA Cluster
# Generated by Ansible
#
# Usage: ./health_check.sh [options]
#
# Options:
#   -c, --config    Path to patroni.yml (default: /etc/patroni/patroni.yml)
#   -v, --verbose   Verbose output
#   -h, --help      Show help

set -e

# Default values
CONFIG="/etc/patroni/patroni.yml"
VERBOSE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -c|--config)
            CONFIG="$2"
            shift 2
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  -c, --config    Path to patroni.yml (default: /etc/patroni/patroni.yml)"
            echo "  -v, --verbose   Verbose output"
            echo "  -h, --help      Show help"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_passed() {
    echo -e "${GREEN}✓${NC} $1"
}

check_failed() {
    echo -e "${RED}✗${NC} $1"
}

# Header
echo "============================================"
echo "PostgreSQL HA Cluster Health Check"
echo "============================================"
echo ""

# 1. Check Patroni service
echo "1. Checking Patroni service..."
if systemctl is-active --quiet patroni; then
    check_passed "Patroni service is running"
else
    check_failed "Patroni service is NOT running"
fi

# 2. Check etcd service
echo ""
echo "2. Checking etcd service..."
if systemctl is-active --quiet etcd; then
    check_passed "etcd service is running"
else
    check_failed "etcd service is NOT running"
fi

# 3. Check etcd cluster health
echo ""
echo "3. Checking etcd cluster health..."
if ETCDCTL_API=3 etcdctl endpoint health --cluster 2>/dev/null | grep -q "is healthy"; then
    check_passed "etcd cluster is healthy"
    if $VERBOSE; then
        ETCDCTL_API=3 etcdctl endpoint status --cluster --write-out=table
    fi
else
    check_failed "etcd cluster health check failed"
fi

# 4. Check PostgreSQL process
echo ""
echo "4. Checking PostgreSQL process..."
if pgrep -x postgres > /dev/null; then
    check_passed "PostgreSQL is running"
else
    check_failed "PostgreSQL is NOT running"
fi

# 5. Check Patroni REST API
echo ""
echo "5. Checking Patroni REST API..."
PATRONI_PORT=$(grep -oP 'listen:\s*\K[0-9.:]+' $CONFIG 2>/dev/null | cut -d: -f2 || echo "8008")
if curl -s "http://localhost:${PATRONI_PORT}/health" > /dev/null 2>&1; then
    check_passed "Patroni REST API is responding"
    
    # Get role from API
    ROLE=$(curl -s "http://localhost:${PATRONI_PORT}/" | jq -r '.role' 2>/dev/null || echo "unknown")
    echo "   Role: $ROLE"
else
    check_failed "Patroni REST API is NOT responding"
fi

# 6. Check cluster status
echo ""
echo "6. Checking cluster status..."
if [ -f "$CONFIG" ]; then
    echo ""
    patronictl -c "$CONFIG" list 2>/dev/null || log_error "Failed to get cluster status"
else
    log_warn "Config file not found: $CONFIG"
fi

# 7. Check replication lag (if replica)
echo ""
echo "7. Checking replication status..."
if [ "$ROLE" == "replica" ]; then
    LAG=$(sudo -u postgres psql -t -c "SELECT COALESCE(pg_last_wal_receive_lsn() - pg_last_wal_replay_lsn(), 0)::bigint;" 2>/dev/null | tr -d ' ')
    if [ -n "$LAG" ]; then
        if [ "$LAG" -lt 1048576 ]; then
            check_passed "Replication lag: ${LAG} bytes (< 1MB)"
        else
            check_failed "Replication lag: ${LAG} bytes (>= 1MB)"
        fi
    fi
else
    log_info "Node is primary, skipping replication lag check"
fi

# 8. Check disk space
echo ""
echo "8. Checking disk space..."
DATA_DIR=$(grep -oP 'data_dir:\s*\K[^\s]+' $CONFIG 2>/dev/null || echo "/var/lib/postgresql")
if [ -d "$DATA_DIR" ]; then
    DISK_USAGE=$(df -h "$DATA_DIR" | tail -1 | awk '{print $5}' | tr -d '%')
    if [ "$DISK_USAGE" -lt 80 ]; then
        check_passed "Disk usage: ${DISK_USAGE}%"
    elif [ "$DISK_USAGE" -lt 90 ]; then
        check_failed "Disk usage: ${DISK_USAGE}% (Warning: > 80%)"
    else
        check_failed "Disk usage: ${DISK_USAGE}% (Critical: > 90%)"
    fi
fi

# Summary
echo ""
echo "============================================"
echo "Health check completed"
echo "============================================"
